[libdefaults]
    default_realm = EXAMPLE.ORG
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true

[realms]
    EXAMPLE.ORG = {
        kdc = samba.example.org
        admin_server = samba.example.org
    }

[domain_realm]
    hub.example.org = EXAMPLE.ORG
    .example.org = EXAMPLE.ORG
    example.org = EXAMPLE.ORG
